sudo: false
matrix:
  include:
    - os: osx
      language: objective-c
    - os: linux
      jdk: oraclejdk8
      language: android
      before_install:
        - export PATH=/usr/local/android-sdk/build-tools/28.0.3/:${PATH}
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-22
    - android-26
    - sys-img-armeabi-v7a-android-N
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-23
    - sys-img-x86_64-google_apis-26
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - nvm install 10.9.0
  - nvm use 10.9.0
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm use system; fi
  - /bin/bash tests/travis.sh
